/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as GuidesCreateRouteImport } from './routes/guides/create'
import { Route as GuidesGuideIdRouteImport } from './routes/guides/$guideId'
import { Route as GuidesGuideIdEditRouteImport } from './routes/guides/$guideId_.edit'
import { Route as GuidesGuideIdEntriesIndexRouteImport } from './routes/guides/$guideId_/entries/index'
import { Route as GuidesGuideIdEntriesCreateRouteImport } from './routes/guides/$guideId_/entries/create'
import { Route as GuidesGuideIdEntriesEntryIdRouteImport } from './routes/guides/$guideId_/entries/$entryId'
import { Route as GuidesGuideIdEntriesEntryIdEditRouteImport } from './routes/guides/$guideId_/entries/$entryId_.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesCreateRoute = GuidesCreateRouteImport.update({
  id: '/guides/create',
  path: '/guides/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesGuideIdRoute = GuidesGuideIdRouteImport.update({
  id: '/guides/$guideId',
  path: '/guides/$guideId',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesGuideIdEditRoute = GuidesGuideIdEditRouteImport.update({
  id: '/guides/$guideId_/edit',
  path: '/guides/$guideId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesGuideIdEntriesIndexRoute =
  GuidesGuideIdEntriesIndexRouteImport.update({
    id: '/guides/$guideId_/entries/',
    path: '/guides/$guideId/entries/',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesGuideIdEntriesCreateRoute =
  GuidesGuideIdEntriesCreateRouteImport.update({
    id: '/guides/$guideId_/entries/create',
    path: '/guides/$guideId/entries/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesGuideIdEntriesEntryIdRoute =
  GuidesGuideIdEntriesEntryIdRouteImport.update({
    id: '/guides/$guideId_/entries/$entryId',
    path: '/guides/$guideId/entries/$entryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesGuideIdEntriesEntryIdEditRoute =
  GuidesGuideIdEntriesEntryIdEditRouteImport.update({
    id: '/guides/$guideId_/entries/$entryId_/edit',
    path: '/guides/$guideId/entries/$entryId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/guides/$guideId': typeof GuidesGuideIdRoute
  '/guides/create': typeof GuidesCreateRoute
  '/user/profile': typeof UserProfileRoute
  '/guides/': typeof GuidesIndexRoute
  '/guides/$guideId/edit': typeof GuidesGuideIdEditRoute
  '/guides/$guideId/entries/$entryId': typeof GuidesGuideIdEntriesEntryIdRoute
  '/guides/$guideId/entries/create': typeof GuidesGuideIdEntriesCreateRoute
  '/guides/$guideId/entries/': typeof GuidesGuideIdEntriesIndexRoute
  '/guides/$guideId/entries/$entryId/edit': typeof GuidesGuideIdEntriesEntryIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/guides/$guideId': typeof GuidesGuideIdRoute
  '/guides/create': typeof GuidesCreateRoute
  '/user/profile': typeof UserProfileRoute
  '/guides': typeof GuidesIndexRoute
  '/guides/$guideId/edit': typeof GuidesGuideIdEditRoute
  '/guides/$guideId/entries/$entryId': typeof GuidesGuideIdEntriesEntryIdRoute
  '/guides/$guideId/entries/create': typeof GuidesGuideIdEntriesCreateRoute
  '/guides/$guideId/entries': typeof GuidesGuideIdEntriesIndexRoute
  '/guides/$guideId/entries/$entryId/edit': typeof GuidesGuideIdEntriesEntryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/guides/$guideId': typeof GuidesGuideIdRoute
  '/guides/create': typeof GuidesCreateRoute
  '/user/profile': typeof UserProfileRoute
  '/guides/': typeof GuidesIndexRoute
  '/guides/$guideId_/edit': typeof GuidesGuideIdEditRoute
  '/guides/$guideId_/entries/$entryId': typeof GuidesGuideIdEntriesEntryIdRoute
  '/guides/$guideId_/entries/create': typeof GuidesGuideIdEntriesCreateRoute
  '/guides/$guideId_/entries/': typeof GuidesGuideIdEntriesIndexRoute
  '/guides/$guideId_/entries/$entryId_/edit': typeof GuidesGuideIdEntriesEntryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/guides/$guideId'
    | '/guides/create'
    | '/user/profile'
    | '/guides/'
    | '/guides/$guideId/edit'
    | '/guides/$guideId/entries/$entryId'
    | '/guides/$guideId/entries/create'
    | '/guides/$guideId/entries/'
    | '/guides/$guideId/entries/$entryId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/guides/$guideId'
    | '/guides/create'
    | '/user/profile'
    | '/guides'
    | '/guides/$guideId/edit'
    | '/guides/$guideId/entries/$entryId'
    | '/guides/$guideId/entries/create'
    | '/guides/$guideId/entries'
    | '/guides/$guideId/entries/$entryId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/guides/$guideId'
    | '/guides/create'
    | '/user/profile'
    | '/guides/'
    | '/guides/$guideId_/edit'
    | '/guides/$guideId_/entries/$entryId'
    | '/guides/$guideId_/entries/create'
    | '/guides/$guideId_/entries/'
    | '/guides/$guideId_/entries/$entryId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  GuidesGuideIdRoute: typeof GuidesGuideIdRoute
  GuidesCreateRoute: typeof GuidesCreateRoute
  UserProfileRoute: typeof UserProfileRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  GuidesGuideIdEditRoute: typeof GuidesGuideIdEditRoute
  GuidesGuideIdEntriesEntryIdRoute: typeof GuidesGuideIdEntriesEntryIdRoute
  GuidesGuideIdEntriesCreateRoute: typeof GuidesGuideIdEntriesCreateRoute
  GuidesGuideIdEntriesIndexRoute: typeof GuidesGuideIdEntriesIndexRoute
  GuidesGuideIdEntriesEntryIdEditRoute: typeof GuidesGuideIdEntriesEntryIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/create': {
      id: '/guides/create'
      path: '/guides/create'
      fullPath: '/guides/create'
      preLoaderRoute: typeof GuidesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$guideId': {
      id: '/guides/$guideId'
      path: '/guides/$guideId'
      fullPath: '/guides/$guideId'
      preLoaderRoute: typeof GuidesGuideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$guideId_/edit': {
      id: '/guides/$guideId_/edit'
      path: '/guides/$guideId/edit'
      fullPath: '/guides/$guideId/edit'
      preLoaderRoute: typeof GuidesGuideIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$guideId_/entries/': {
      id: '/guides/$guideId_/entries/'
      path: '/guides/$guideId/entries'
      fullPath: '/guides/$guideId/entries/'
      preLoaderRoute: typeof GuidesGuideIdEntriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$guideId_/entries/create': {
      id: '/guides/$guideId_/entries/create'
      path: '/guides/$guideId/entries/create'
      fullPath: '/guides/$guideId/entries/create'
      preLoaderRoute: typeof GuidesGuideIdEntriesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$guideId_/entries/$entryId': {
      id: '/guides/$guideId_/entries/$entryId'
      path: '/guides/$guideId/entries/$entryId'
      fullPath: '/guides/$guideId/entries/$entryId'
      preLoaderRoute: typeof GuidesGuideIdEntriesEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$guideId_/entries/$entryId_/edit': {
      id: '/guides/$guideId_/entries/$entryId_/edit'
      path: '/guides/$guideId/entries/$entryId/edit'
      fullPath: '/guides/$guideId/entries/$entryId/edit'
      preLoaderRoute: typeof GuidesGuideIdEntriesEntryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  GuidesGuideIdRoute: GuidesGuideIdRoute,
  GuidesCreateRoute: GuidesCreateRoute,
  UserProfileRoute: UserProfileRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  GuidesGuideIdEditRoute: GuidesGuideIdEditRoute,
  GuidesGuideIdEntriesEntryIdRoute: GuidesGuideIdEntriesEntryIdRoute,
  GuidesGuideIdEntriesCreateRoute: GuidesGuideIdEntriesCreateRoute,
  GuidesGuideIdEntriesIndexRoute: GuidesGuideIdEntriesIndexRoute,
  GuidesGuideIdEntriesEntryIdEditRoute: GuidesGuideIdEntriesEntryIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
